### ISSUE TITLE
KeyError: 'custom'

### ISSUE THREAD

**Issue by quozl** [sugarlabs/terminal-activity#41]
```log
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 746, in __canvas_map_cb
    self.read_file(self._jobject.file_path)
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 523, in read_file
    self._create_tab(tab_state)
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 360, in _create_tab
    self._configure_vt(vt)
  File "/usr/share/sugar/activities/Terminal.activity/terminal.py", line 625, in _configure_vt
    fg_color = self._theme_colors[self._theme_state]['fg_color']
KeyError: 'custom'
```

Terminal-47 +git master on Sugar 0.117

**Comment by Saumya-Mishra9129** [comment]
@quozl Can you tell how to reproduce this error.??

**Comment by quozl** [comment]
Not off-hand, sorry.  The traceback is very clear though.  I suggest you read the traceback carefully, then instrument the code at the failed line and verify you can execute it, then figure out where the theme state is set, and under what conditions.

**Comment by Saumya-Mishra9129** [comment]
@quozl It seems like you tested with any old commit, Because the code is modified in d2d243cff471a452cce9617ff44709da29ebc29d . I tested with master and Terminal-47 didnt get this error.

**Comment by quozl** [comment]
Specifically, the line numbers in the traceback do not match git _master_ at the time of the issue, and there wasn't a pull request merged in the meanwhile.  Thanks.
